version: '3'

services:
  nginx:
    image:
      nginx:latest
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./nginx/nginx:/etc/nginx.conf.d
    depends_on:
      - backend
  backend:
    container_name: back
    build:
      context: .
      dockerfile: ./back/Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 back.wsgi:application
    expose:
      - "8000"
    volumes:
    - .:/app
    restart: always
