# Generated by Django 4.2.1 on 2023-06-04 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("name", models.CharField(max_length=20)),
                (
                    "nickname",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("photo", models.ImageField(blank=True, upload_to="")),
            ],
        ),
    ]
